spring:
  profiles:
    active: dev

# config读取本地配置,不同环境使用 include， 或者使用dev,native
#spring:
#  profiles:
#    active: dev,native
#    include: dev

#  cloud:
#    config:
#      native:
#        searchLocations: file:./config