server:
  port: 7018

spring:
  application:
    name: springboot-rocketmq

rocketmq:
  # ##consumer
  consumer:
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
    # 消费线程最大数量
    consumeThreadMax: 64
    # 消费线程最小数量
    consumeThreadMin: 20
    groupName: ${spring.application.name}
    # #该应用是否启用消费者
    isOnOff: on
    # mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    # 该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    #rocketmq.consumer.topics=DemoTopic~*;
    topics: DemoTopic

  # ##producer
  producer:
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: ${spring.application.name}
    # 该应用是否启用生产者
    isOnOff: on
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
