server.port: 7016

spring:
  application:
    name: sentinel

  cloud:
    sentinel:
      eager: true
      transport:
        port: 8080
        dashboard: 127.0.0.1:8080
        heartbeat-interval-ms: 500
