server:
  port: 7012
spring:
  application:
    name: service-zipkin
  zipkin:
    base-url: http://120.0.0.1:9001

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000//eureka/
    # \u8FD9\u4E2A\u624D\u662F\u91CD\u70B9
    fetch-registry: true
    register-with-eureka: true